### ISSUE TITLE
Broken Outdoor Lighting in Alpha Labs 2

### ISSUE THREAD

**Issue by GlacialTurtle** [RobertBeckebans/RBDOOM-3-BFG#397] opened 2017-08-30 20:24 UTC
A section in Alpha Labs 2 where a demon spawns and breaks a window has broken lighting for the visible outdoor area.

https://imgur.com/a/09wYz

Tested with 1.1.0-preview3, Ubuntu 16.04 with Mesa 17.1 from Padoka PPA, AMD HD7770 2GB, AMD FX6350, 8GB RAM

**Comment by BielBdeLuna** [comment] 2017-08-30 21:24
broken? originally this area was displayed completely black because the engine lacked the ambient pass of the renderer, I think this area was lighted using only a single ambient light, that's the reason there is only ambient light on the weapons in the first pic.

**Comment by GlacialTurtle** [comment] 2017-08-30 22:50
Either lighting or textures, compare to this:

https://youtu.be/aXlJnOozA9U?t=383

or in the original Doom 3:

https://youtu.be/KBPiJld4OSo?t=224

No shadows in outdoor area where there should be and no apparent bump mapping (or is the term normal mapping), it looks like when a game is set to "fullbright" mode, but only in the outdoor portion, the rest of the area seems fine.

**Comment by BielBdeLuna** [comment] 2017-08-31 00:30
in d3bfg there where no ambient term, I know because I pointed the error, when we solved it, if you download the game from steam, you'll see that black mess you see in the video, that's the ambient light missing, there are several things missing from the BFG edition that where present in vanilla doom3, one of them the ambient term (another, some particles being affected by light, look at the souls in the Hell level, yes those black things flying are failing textured particles)

in doom3 the ambient term has a directionality (up, everything is ambient-lighten as if there where a light above), this is not ambient light, ambient light is direction-less light, in doom3 those caused the coal miner dirty hands when the player is in the influence of and ambient light, there where two solutions from the modding teams back in vanilla times, one to represent ambient light as light emanating from the player point of view, and another, the one in RBDoom3BFG, where Ambient light is direction-less, that is what you see, that "full bright" mode you say, is caused by D software lighting that part of the level only with an ambient light and no direct light lighting the shadows, other than the sun, let's say it's not Doom3 finest hour.

that's doom3 dirty coal miner ambient light term: http://imgur.com/a/Fkr0B

If you want something similar to that gritty level, add SSAO with r_useSSAO 1

**Comment by GlacialTurtle** [comment] 2017-08-31 03:57
> that's doom3 dirty coal miner ambient light term: http://imgur.com/a/Fkr0B is it better? I don't think so, and modder teams in time abandoned this to pursue the "full bright" ambient term.

This is completely nonsensical to me. Overly bright orange with no shadows and no visible normal mapping that doesn't remotely resemble how outdoor Mars areas look in the rest of the game is better?

There is no "black mess", the area is properly lit (even if it means it is dark) and the details that are meant to be visible are there e.g. the small bumps and crevices from normal mapping in both original Doom 3 and Doom 3 BFG (albeit the textures on the cliffs are not amazing). In the original screenshot literally none of this detail is visible, and the scene appears abnormally bright compared to every other scene in the game. Whether or not the ambient light is *technically* correct in the abstract doesn't matter much if areas in the game like that are clearly not made with this in mind and leads to broken lighting that is not what is intended for the game to look. Not even the hand and gun are lit correctly when you go out through the window with no visible normal mapping details that should be there.

**Comment by BielBdeLuna** [comment] 2017-08-31 07:01
that's because the engine is used for modding also, not just for representing the game Doom3, it might not make sense for the game, where this ambient lightning there might look wrong, but for other uses, it's fine, the screen shots I posted are from vanilla Doom3, so that is how it's supposed to look like, that's the base.

besides, why do you expect to see normal map details when things are lighted with an ambient light only? does this make any sense to you?

**Comment by GlacialTurtle** [comment] 2017-08-31 07:26
Then surely it makes more sense to add a new light that has the properties you want, rather than changing an existing one that messes up how the base game (and potentially mods that were made with his behaviour in mind) is intended to look.

> besides, why do you expect to see normal map details when things are lighted with an ambient light only? does this make any sense to you?

Yes? If that's how it's meant to look in the base game, then yes it makes sense.

**Comment by BielBdeLuna** [comment] 2017-08-31 07:59
ambient isn't a new light type, is integral to the Blinn Phong shading model, ambient light term should have isotropic luminance, that means not view dependant, nor direction dependant. 
Besides, if the original game failed at having this, why not amend the error? this is the same as having the gamma-corrected colour math. it wasn't in the original game, but it makes sense to have it in the improved engine.

**Comment by GlacialTurtle** [comment] 2017-09-01 17:23
> Besides, if the original game failed at having this, why not amend the error? this is the same as having the gamma-corrected colour math. it wasn't in the original game, but it makes sense to have it in the improved engine.

And in that case, you have the same outcome, assuming what you're referring to is the same thing that broke the flash light, imp fireball effects, etc. - game assets were not made with this behaviour in mind, so fixing the error to be technically correct breaks certain visuals just as much as it fixes how it should work "on paper". It would be nice if these new behaviours weren't forced with the use of shadow mapping and HDR, seeing as they clearly break multiple visuals in the game.

Would it not be possible to at least add a toggle between old and new light behaviours? Like a compatibility toggle to switch to old gamma and ambient light behaviour to ensure everything looks correct for the base game, but you can still have the new behaviour by default, or set it for default for anything that isn't vanilla Doom 3 BFG/RoE.

**Comment by BielBdeLuna** [comment] 2017-09-01 17:36
The engine it's the personal project of @RobertBeckebans and if he wants to incorporate HDR he is free to do so, if you want the engine to fit your needs you are free to fork it.
What you want is an easy fix, just add the diffuse term multiplying back to the ambient shaders:
Add `* lambert` to `result.color.xyz` in all the *.pixel files related to ambient light interaction.

**Comment by GlacialTurtle** [comment] 2017-09-01 18:39
Thank you, I will try this.

**Comment by KungFuJesus** [comment] 2017-11-26 19:17
The lighting engine does seem to be behave goofy in some places, I see doors flash and saturate with overhead lights for seconds at a time - sometimes the light will also basically drop to zero in other places (but if you exit and come back, it's somewhat reasonably lit).  Flashlight helps for when it drops to near zero light, but it's not always clear why the light went so low.

**Comment by RobertBeckebans** [comment] 2020-05-31 21:06
All these problems have been fixed in the PBR2 branch.

**Closed by RobertBeckebans** 2020-05-31 21:06 UTC
