### ISSUE TITLE
HDR lighting in linear RBG + ACES Film Tonemapping

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#285] opened 2016-01-13 01:38 UTC
Light equations have been wrong in games for more than 14 years.
See http://http.developer.nvidia.com/GPUGems3/gpugems3_ch24.html

This is also a requirement for the Physically Based Rendering standard.

Current results: http://imgur.com/a/dKfLH

**Comment by RobertBeckebans** [comment] 2016-01-13 01:41
TBH it is amazing how the 10 years old assets can look like with correct lighting. The old shaders just make the game cartoony.

**Comment by aFoxNamedMorris** [comment] 2016-01-13 01:46
Wha... With the progress that is being made here... there's less and less an excuse for the Doom 3 (2004) modding community to avoid moving to BFG Edition. Fabulous.

**Comment by BielBdeLuna** [comment] 2016-01-13 04:11
this is escellent looking! :+1: :+1: :+1:

**Comment by romulus2k4** [comment] 2016-01-19 18:23
I compiled this today, and it seems this is totally broken on AMD, can anyone else confirm this?

**Comment by RobertBeckebans** [comment] 2016-01-19 19:21
Could you make a proper bug report with screenshots and a qconsole.log pastebin?
Everything else is just wasting time.

**Comment by romulus2k4** [comment] 2016-01-20 16:05
OKay, I have done as you have asked. Here are three screenshots I took from "Alpha Labs 1."

http://imgur.com/a/HqTeh

And here's the qconsole.log: https://paste.ee/p/jytT2

**Comment by Yetta1** [comment] 2016-01-20 16:28
Your pc may be on acid. This issue may be linked to the other AMD based post. The only part of your log that I believe may be the cause is the following.

```------------- Warnings ---------------
during DOOM 3: BFG Edition initialization...
WARNING: Unable to open resource file maps/_startup.resources
WARNING: file renderprogs/interaction.pixel, line 30: file 'renderprogs/BRDF.inc' not found
WARNING: file renderprogs/interaction.pixel, line 32: Could not strip dead code -- unknown token uniform
 
WARNING: file renderprogs/interactionSM.pixel, line 30: file 'renderprogs/BRDF.inc' not found
WARNING: file renderprogs/interactionSM.pixel, line 32: Could not strip dead code -- unknown token uniform
```

Seems a lot of the fragment shader fails are related to the BRDF shader.

**Comment by BielBdeLuna** [comment] 2016-01-20 16:54
I've just compiled it this looks excellent!

**Comment by Yetta1** [comment] 2016-01-20 16:56
@BielBdeLuna Any ideas about the BRDF issue for AMD users? The code fails to compile on VS 2013 on my system, so I can't check it out :(, Screenshots Robert linked looks great though.

**Comment by BielBdeLuna** [comment] 2016-01-20 17:18
I'm not on Windows sorry, so IDK.
No idea why Visual Studio is needed for, why you need a M$ program to make programs work on their OS? Users and sufferers of Windows, revolt against your oppressors! 
And about BRDF.inc missing, I have it in my renderprogs, have you copied the base folder from the source folder to the game folder, maybe Robert hasn't included his new GLSL code as hardcoded source yet, he's been doing so with other additions he has made, so you won't need the renderprogs folder once he has done it, but for the moment you might need to copy it.

**Comment by Yetta1** [comment] 2016-01-20 17:29
@BielBdeLuna Lol another guy from another post also posted about the renderprogs files. I feel you about the whole M$ thing, I also use Linux on my other machines, but those GPU's are not good for anything 3D. I only use Windows on my main system for some games that really don't work with Wine. Thankfully that will change in the future as more devs make DX games more compatible. Just happy AMD refused M$'s offer to buy the company, they may be struggling financially, but always innovate computing, can't wait for Zen, now all we need is proper drivers.

**Comment by Yetta1** [comment] 2016-01-20 17:49
@romulus2k4 As suggested by a user on another issue, try moving the renderprogs folder into your base folder.

**Comment by romulus2k4** [comment] 2016-01-20 18:08
I don't understand, I already have the "renderprogs" folder in my "base" folder?

**Comment by Yetta1** [comment] 2016-01-20 18:16
@romulus2k4 If I understand correctly the source code already has built in renderprogs in the source code, then it creates the renderprogs folder and adds the render/shader code. So it may be because the renderprogs that are included separately with the new shaders needs to replace the others. So try copying over the renderprogs included in the RBdoom3-master and see if that works.

**Comment by Yetta1** [comment] 2016-01-20 19:45
Just compiled after the ffmpeg fix, the game looks great, way brighter than the old D3. It kind of makes me think of the SOMA game. There are only three issues I've found, an average FPS of 15, died by jumping into a crate with no enemies around (was funny), and of course the old light in the other room making the door glow. I'll open the map at some late date in radiant and take a look at those doors. Maybe it's not occluding like it should.

**Comment by BielBdeLuna** [comment] 2016-01-20 19:47
if you use git to get the source in your computer take a look on what has downloaded, if it has downloaded any file in the base folder in the source folder then you have to copy the base folder from the source over the base folder in the game folder

**Comment by Yetta1** [comment] 2016-01-20 19:54
@BielBdeLuna That makes sense. I'll check the maps and do fixes, however I'm uncertain if we are allowed to redistribute the fixed maps as some sort of community patch.

**Comment by BielBdeLuna** [comment] 2016-01-20 20:22
you can fix a map for yourself but you can't redistribute id Software creation, you're free to create patches to extract and change the maps though, but I think this error could be accepted as a bug in the map making, and let it pass, another thing would be to hunt the error in the portal system and kill it. the portal system is known to some times block off rooms inside of buildings from lights that are huge (like the sun) so that their center is several portals away. And so the light should enter but there is an invisible barrier that leaves the room in shadows, this invisible barrier is the portal.

this doesn't happen with ambient lights, like with fogs, because in the portal system there is an special requirement to not kill off those sort of lights if the portal is "fogged".

**Comment by nbohr1more** [comment] 2016-01-20 20:59
Yeah, use something like WinMerge to create a patch and have end-users patch the x.map files. 

It's possible that light leaking is due to precision issues in the latest MSVC versions (they don't support x87 FP instructions and thus reduce precision from 90-bit to whatever RBDOOM3 uses). At least we saw that in Vanilla (The Dark Mod) with MSVC 2013. (That and borked epsilon operations, and compiler optimizations that removed valid code...)

**Comment by BielBdeLuna** [comment] 2016-01-20 21:03
I think it's not a MSVC issue as I in linux also see this.

**Comment by Yetta1** [comment] 2016-01-20 21:13
I'll have to look into WinMerge, not sure how to do patches.

**Closed** 2020-05-31 19:54 UTC
Labels: enhancement
