### ISSUE TITLE
Music in Doom 1 & 2 don't loop

### ISSUE THREAD

**Issue by Szalacinski** [RobertBeckebans/RBDOOM-3-BFG#322] opened 2016-06-07 19:52 UTC
I tested the first and second levels.  The music doesn't loop.  The music on the level complete screen seems to do so, however.

**Comment by Szalacinski** [comment] 2016-06-07 20:02
I just tested Doom 2.  It does the same thing.

**Comment by Szalacinski** [comment] 2016-06-07 20:31
This probably isn't intentional, because I just pulled up PrBoom+ with the shareware version of Doom 1, and it loops just fine.

**Comment by Szalacinski** [comment] 2016-06-08 03:52
Unlike my other closed issue, this bug persists after the Steam integrity check.

**Comment by Szalacinski** [comment] 2016-06-08 19:16
Also, this doesn't seem to appear in the 1.0.3 version.  Only the latest version pulled from git.

**Comment by RobertBeckebans** [comment] 2020-05-31 21:58
Confirmed that this happens with OpenAL builds and Windows 10 XAudio builds.

**Comment by SRSaunders** [comment] 2023-07-03 21:32
Is this still an issue?  I can't duplicate this defect in the current master.  Classic music loops properly for me for Windows XAudio and macOS OpenAL (have not tested on linux).

**Comment by RobertBeckebans** [comment] 2024-07-18 20:21
This seems to be fixed on Linux as well.

**Closed by RobertBeckebans** 2024-07-18 20:21 UTC
Labels: bug
