### ISSUE TITLE
Segmentation fault at every exit

### ISSUE THREAD

**Issue by l29ah** [RobertBeckebans/RBDOOM-3-BFG#494] opened 2020-10-13 01:59 UTC
It's not a big deal, but it pollutes my system with core dumps! :)
The game has to load and play the campaign a lil for it to start segfaulting at exit.
console says
```
...
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
shutdown terminal support
Segmentation fault (core dumped)
```
gdb says
```
#0  0x000055aab5ae689f in idSaveLoadParms::~idSaveLoadParms() ()
#1  0x000055aab5afbda7 in idSaveGameProcessorLoadFiles::~idSaveGameProcessorLoadFiles() ()
#2  0x000055aab5aeceb5 in idSessionLocal::~idSessionLocal() ()
#3  0x00007fec866cd6f3 in __run_exit_handlers () from /lib64/libc.so.6
#4  0x00007fec866cd8ac in exit () from /lib64/libc.so.6
#5  0x000055aab5affa2b in Posix_Exit(int) ()
#6  0x000055aab5affa8d in Sys_Quit() ()
#7  0x000055aab59b8315 in idMenuHandler_Shell::HandleExitGameBtn()::idSWFScriptFunction_QuitDialog::Call(idSWFScriptObject*, idSWFParmList const&) ()
#8  0x000055aab575fe8c in idSWFScriptFunction_Script::Run(idSWFScriptObject*, idSWFStack&, idSWFBitStream&) ()
#9  0x000055aab5761e08 in idSWFScriptFunction_Script::Call(idSWFScriptObject*, idSWFParmList const&) ()
#10 0x000055aab5734d36 in idSWF::HandleEvent(sysEvent_t const*) ()
#11 0x000055aab5448bf8 in idCommonDialog::HandleDialogEvent(sysEvent_t const*) ()
#12 0x000055aab543c1ab in idCommonLocal::ProcessEvent(sysEvent_t const*) ()
#13 0x000055aab5498252 in idEventLoop::RunEventLoop(bool) ()
#14 0x000055aab54c52af in idCommonLocal::Frame() ()
#15 0x000055aab53fd31d in main ()
```

**Comment by r-a-sattarov** [comment] 2020-10-13 18:11
Maybe this PR https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/378 will fix it?

**Comment by RobertBeckebans** [comment] 2020-11-05 09:26
I tested this yesterday on Kubuntu 20.10 and I couldn't reproduce it.

**Comment by r-a-sattarov** [comment] 2020-11-05 21:48
> I tested this yesterday on Kubuntu 20.10 and I couldn't reproduce it.

Try to launch the game, change the graphics settings in the game (for example, change the resolution) and automatically restart the game.
I often get an error at this point (I use OS Linux Elbrus 6.0).

**Comment by RobertBeckebans** [comment] 2021-04-29 14:43
This should be fixed in the current master.

**Closed** 2022-01-22 13:33 UTC
Labels: bug
