### ISSUE TITLE
RBDOOM 3 BFG has inherited the infamous OpenGL first launch bug.

### ISSUE THREAD

**Issue by ableistsl** [RobertBeckebans/RBDOOM-3-BFG#675] opened 2022-05-29 16:48 UTC
RBDOOM 3 BFG has inherited the infamous OpenGL first launch bug that interferes with launching the game unless it's launched with set r_fullscreen "0"
```
QA Timing INIT: 000001ms
RBDOOM 3 BFG 1.4.0.1401 win-x64 Mar  6 2022 11:27:12
10 MHz generic CPU with SSE & SSE2
Winsock Initialized
Found interface: {2A2D3CC1-F122-4261-814B-06D235C727A9} GIGABYTE 10Gbit Network by AQtion AQC107 - 0.0.0.0 NULL netmask - skipped
Found interface: {15FDBC19-F45A-4330-AB63-09C564FEDBBC} Intel(R) I211 Gigabit Network Connection - 0.0.0.0 NULL netmask - skipped
Found interface: {A0B0592F-7B6C-41B9-8358-62CC175C9D9F} Bluetooth Device (Personal Area Network) - 0.0.0.0 NULL netmask - skipped
Found interface: {15AE7ED9-2694-4705-8EC0-A76395E4A071} Intel(R) Wi-Fi 6E AX210 160MHz - 10.0.0.249/255.255.255.0
Found interface: {43CBC87E-97D1-4386-8491-1F5C134DB10F} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {BA93C9EC-277E-4671-A01A-D1A514BF24E9} Microsoft Wi-Fi Direct Virtual Adapter #2 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Current search path:
C:\Users\User\Saved Games\id Software\RBDOOM 3 BFG/base
C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
execing default.cfg
couldn't exec D3BFGConfig.cfg
couldn't exec autoexec.cfg
----- R_InitOpenGL -----
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:1
...registered window class
...registered fake window class
Using GLEW 2.0.0
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:1
Using GLEW 2.0.0
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
Unknown command 'vid_restart'
Unable to initialize OpenGL
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
```

**Comment by MadDeCoDeR** [comment] 2022-06-18 20:43
The issue is not with OpenGL. But with the engine itself. The engine expects your monitor to support either 60Hz or 120Hz. Failing to do that and the game fails to boot up

**Comment by RobertBeckebans** [comment] 2023-02-25 11:20
This should be fixed with the latest code in the master branch.

**Closed by RobertBeckebans** 2023-02-25 11:20 UTC
