### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by OlegAckbar** [RobertBeckebans/RBDOOM-3-BFG#911] opened 2024-07-07 12:04 UTC
```
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp: In member function 'virtual void idCommonLocal::Printf(const char*, ...)':
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:883:30: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  883 |                 STDIO_PRINT( "", "" );
      |                              ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:176:17: note: in definition of macro 'STDIO_PRINT'
  176 |         printf( pre );                                  \
      |                 ^~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:883:34: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  883 |                 STDIO_PRINT( "", "" );
      |                                  ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:178:17: note: in definition of macro 'STDIO_PRINT'
  178 |         printf( post );                                 \
      |                 ^~~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:883:34: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  883 |                 STDIO_PRINT( "", "" );
      |                                  ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:179:16: note: in definition of macro 'STDIO_PRINT'
  179 |         printf(post);           \
      |                ^~~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp: In member function 'virtual void idCommonLocal::DPrintf(const char*, ...)':
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:905:38: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  905 |                         STDIO_PRINT( "", "" );
      |                                      ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:176:17: note: in definition of macro 'STDIO_PRINT'
  176 |         printf( pre );                                  \
      |                 ^~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:905:42: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  905 |                         STDIO_PRINT( "", "" );
      |                                          ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:178:17: note: in definition of macro 'STDIO_PRINT'
  178 |         printf( post );                                 \
      |                 ^~~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:905:42: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  905 |                         STDIO_PRINT( "", "" );
      |                                          ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:179:16: note: in definition of macro 'STDIO_PRINT'
  179 |         printf(post);           \
      |                ^~~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp: In member function 'virtual void idCommonLocal::VerbosePrintf(const char*, ...)':
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:918:38: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  918 |                         STDIO_PRINT( "", "" );
      |                                      ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:176:17: note: in definition of macro 'STDIO_PRINT'
  176 |         printf( pre );                                  \
      |                 ^~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:918:42: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  918 |                         STDIO_PRINT( "", "" );
      |                                          ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:178:17: note: in definition of macro 'STDIO_PRINT'
  178 |         printf( post );                                 \
      |                 ^~~~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:918:42: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  918 |                         STDIO_PRINT( "", "" );
      |                                          ^~
/home/oleg/Desktop/RBDOOM-3-BFG/neo/tools/compilers/main_posix.cpp:179:16: note: in definition of macro 'STDIO_PRINT'
  179 |         printf(post);           \
      |                ^~~~
cc1plus: some warnings being treated as errors
make[2]: *** [tools/compilers/CMakeFiles/rbdmap.dir/build.make:90: tools/compilers/CMakeFiles/rbdmap.dir/main_posix.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:450: tools/compilers/CMakeFiles/rbdmap.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by DistantThunder** [comment] 2024-07-07 13:47
Duplicate of: #909 

Use CLANG for now, on Arch it should be:
`CC=/bin/clang CXX=/bin/clang++ ./cmake-linux-release.sh`

**Closed** 2024-07-10 18:06 UTC
