### ISSUE TITLE
commit 988420c breaks Arch Linux SDL2

### ISSUE THREAD

**Issue by noabody** [RobertBeckebans/RBDOOM-3-BFG#469] opened 2020-04-19 17:43 UTC
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Manjaro Linux 20.0

**Is this for single player or multiplayer?**
Build issue

**Description of the bug (and if possible, steps to reproduce the bug):**
commit 988420c breaks Arch Linux build. ${SDL2_INCLUDE_DIRS} and ${SDL2_LIBRARIES} return no value.

**What did you expect to happen instead?**
Expected SDL2 link libraries and includes to be available during compilation. SDL.h not found.

This patch solves the problem and the resolution was expanded by a sister report I made regarding OpenJediAcademy.
https://github.com/JACoders/OpenJK/issues/1034

```diff
diff --git a/neo/CMakeLists.txt b/neo/CMakeLists.txt
index 1a36eef6..fcb2c88e 100644
--- a/neo/CMakeLists.txt
+++ b/neo/CMakeLists.txt
@@ -1599,6 +1599,8 @@ else()
 
 		if(SDL2)
 			find_package(SDL2 REQUIRED)
+			get_target_property(SDL2_INCLUDE_DIRS SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES)
+			get_target_property(SDL2_LIBRARIES SDL2::SDL2 IMPORTED_LOCATION_NOCONFIG)
 			include_directories(${SDL2_INCLUDE_DIRS})
 			set(SDLx_LIBRARY ${SDL2_LIBRARIES})
 		else()
```

**Comment by coldtobi** [comment] 2020-04-19 18:11
What version of SDL2 do you have in Manjaro linux? 
(it should be Debian based, but only recently there was a new enough SDL2 in Debian. Might be that you need a newer SDL…)

**Comment by noabody** [comment] 2020-04-19 20:26
Manjaro Lysia 20.0 and its SDL2 version is 2.0.12

**Comment by coldtobi** [comment] 2020-04-20 06:50
This seems to be an issue with either
- Manajao 
- SDL2 2.0.12

Here, in Debian, it builds fine with 2.0.10…
Maybe you're seing https://bugzilla.libsdl.org/show_bug.cgi?id=4116?

**Comment by noabody** [comment] 2020-04-20 13:41
That's it alright but the Debian solution looks like a hack.  

Arch builds SDL2 with almost a pure vanilla config [Arch SDL2 PKGBUILD](https://git.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/sdl2)
The only change they're making is this:
-  sed -i "s/libSDL2\.a/libSDL2main.a/g" "$pkgdir"/usr/lib/cmake/SDL2/SDL2Targets-noconfig.cmake

Debian isn't packaging all of the config files [libsdl2-dev_2.0.10 eoan](https://packages.ubuntu.com/eoan/amd64/libsdl2-dev/download), just this one:

sdl2-config.cmake
```
# sdl2 cmake project-config input for ./configure scripts

set(prefix "/usr") 
set(exec_prefix "${prefix}")
set(libdir "${prefix}/lib/x86_64-linux-gnu")
set(SDL2_PREFIX "/usr")
set(SDL2_EXEC_PREFIX "/usr")
set(SDL2_INCLUDE_DIRS "${prefix}/include/SDL2")
set(SDL2_LIBRARIES " -lSDL2")
string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
```
While that does export the proper variable for backward compatibility it doesn't make sense for Debian to create a hack, then advocate that to developers.  If they want to promote pure CMake language, as SDL2 appears to be doing, then that would be okay.

I'm a hobbyist so I make my own packages.  Arch developers are beginning to make patches as was done for OpenJK:
[sdl2-cmake.patch](https://aur.archlinux.org/cgit/aur.git/plain/sdl2-cmake.patch?h=openjk-git)

This isn't really a solution as was noted in https://bugzilla.libsdl.org/show_bug.cgi?id=4116.

For my own purposes, I prefer a targeted *perl* in-line replacement in my PKGBUILD:
```
perl -pi -e 's|(find_package\(SDL2 REQUIRED\).*$)|\1\n\t\t\tget_target_property(SDL2_INCLUDE_DIRS SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES)\n\t\t\tget_target_property(SDL2_LIBRARIES SDL2::SDL2 IMPORTED_LOCATION_NOCONFIG)|gi' "$pkgname"/neo/CMakeLists.txt
```

**Comment by JanSimek** [comment] 2020-04-29 10:03
Shouldn't this suffice?

```diff
diff --git a/neo/CMakeLists.txt b/neo/CMakeLists.txt
index 1a36eef..74af985 100644
--- a/neo/CMakeLists.txt
+++ b/neo/CMakeLists.txt
@@ -1599,8 +1599,7 @@ else()
 
                if(SDL2)
                        find_package(SDL2 REQUIRED)
-                       include_directories(${SDL2_INCLUDE_DIRS})
-                       set(SDLx_LIBRARY ${SDL2_LIBRARIES})
+                       set(SDLx_LIBRARY SDL2::SDL2)
                else()
                        find_package(SDL REQUIRED)
                        include_directories(${SDL_INCLUDE_DIR})
```

It should both link the library and also include the header directory. Works for me on Arch using SDL 2.0.12

**Comment by xcom169** [comment] 2020-12-31 14:42
It's also a problem for me on Manjaro.

**Comment by HarrievG** [comment] 2021-01-15 21:37
I can confirm @JanSimek solution also works for MSVC + vs2019 cmake + vcpkg 
https://github.com/HarrievG/d3wasm/commit/97fa784aa642226ce4da8abf12cb02000417fab8

**Comment by KiralyCraft** [comment] 2021-04-10 09:07
I can also confirm @JanSimek 's solution works on Manjaro. Many thanks!

**Comment by coldtobi** [comment] 2021-04-10 11:20
> Shouldn't this suffice?
(...)
This patch works for /me on Debian sid as well.

**Comment by DanielGibson** [comment] 2021-04-13 19:30
> Possibly this makes minimum SDL2 version to be 2.0.12 or .14

That would be very bad as it excludes people using debian stable or Ubuntu 20.04LTS (or older).

(in dhewm3 I just went back to shipping a FindSDL2.cmake, as that seemed to work best)

**Comment by coldtobi** [comment] 2021-04-14 07:08
> > Possibly this makes minimum SDL2 version to be 2.0.12 or .14

Note that I did not verify that. Said that, the PR I supplied originally compiles with an older SDL. (I wrote 2.0.4 in that PR, did not recheck) 

> That would be very bad as it excludes people using debian stable or Ubuntu 20.04LTS (or older).

(Only when they want hack on it. Otherwise I'd suggest them to use the packages from the distribution…)
 
> (in dhewm3 I just went back to shipping a FindSDL2.cmake, as that seemed to work best)

Having a FindSDL2.cmake in the projects creates a lot of problems, especially for distributions… So it is good that SDL ships them know and projects are encouraged to drop theirs.  Especially as those FindSDL2.cmake are usually severley outdated…
In Debian I actually carrry a patc  in dhewm3 because of a broken a FindSDL. (https://salsa.debian.org/games-team/dhewm3/-/blob/master/debian/patches/30-SDL2-CMake.patch)

**Comment by DanielGibson** [comment] 2021-04-14 08:02
> Only when they want hack on it.

Also if they just want to *use* a current version of the sourceport.
I know I do - I'm happy with using a stable LTS distro and not updating everything all the time, but I want to use (more) current versions of source ports, because usually they make great improvements over the years.

>  So it is good that SDL ships them know and projects are encouraged to drop theirs

In theory, yes, in practice unfortunately SDL screwed it up and ships two incompatible cmake configs, and some distros use the one and others the other, and maybe their behavior even changed between SDL releases.
For distro packages this might not matter, because when packaging a new $sourceport package you don't have to care about the SDL2 version of the distros current stable release, as that new package will never land there - but as a maintainer of a sourceport it's important that it can be built on the commonly used Linux distros, including stable and LTS versions (which ship years old versions of SDL2 and other libs).

> In Debian I actually carrry a patc in dhewm3 because of a broken a FindSDL

What's going wrong with the custom findsdl? I haven't tried it on debian in a while, but on ubuntu and raspbian I never had problems with it.
Maybe there even is a way to support *both* SDL2s sdl2-config.cmake **and** SDL2Config.cmake *of all the still relevant SDL2 versions* (i.e. at least back to 2.0.8), but it sure isn't straightforward.

**Comment by coldtobi** [comment] 2021-04-14 08:27
> What's going wrong with the custom findsdl?

smvc sumarized it very well here: https://github.com/JACoders/OpenJK/pull/1033

**Comment by DanielGibson** [comment] 2021-04-14 18:08
> smvc sumarized it very well here: JACoders/OpenJK#1033

That explains why using `sdl2-config.cmake` from libsdl2-dev is preferable (ignoring the existence of SDL2Config.cmake in other distros), but not how the supplied FindSDL2.cmake breaks the build for debian packages.

Just to be clear: Was removing FindSDL2.cmake necessary to make dhewm3/RBDoom3BFG build on debians build servers (or whatever), or was it just done because it's considered "the right thing to do"?

> Is the idea to switch to glfw, or at least add it as an option and/or as default, the better one in the long run?

no.

**Comment by DanielGibson** [comment] 2021-04-15 04:22
I raised this issue at https://discourse.libsdl.org/t/how-is-sdl2-supposed-to-be-used-with-cmake/31275 - hopefully someone there has an idea how to not ship your own FindSDL2.cmake and still remain compatible with common Linux distros like Ubuntu 20.04 or Arch Linux.

I also looked it up, using `SDL2::SDL2` indeed only works with SDL2 2.0.12 or newer (or on distros providing SDL2Config.cmake, like Arch Linux) - even Ubuntu 20.04 ships 2.0.10 (and sdl2-config.cmake) so neither `SDL2::SDL2` nor `SDL2_LIBRARIES`/`SDL2_INCLUDES` by themselves are acceptable options.

**Comment by coldtobi** [comment] 2021-04-15 05:26
> or `SDL2_LIBRARIES`/`SDL2_INCLUDES` by themselves are acceptable options.

SDL2_LIBRARIES`/`SDL2_INCLUDES works with standard Debian*packages since at least 2.0.10, probably (I say because I did not test it) even 2.0.4 (See the PR I opened at that time); so Ubuntu 20.0.4 should work, since Ubuntu is a derivative of Debian and Ubuntu generaly use the Debian's packaging -- I've verified that in this case they do not ship any Ubuntu specific patch to the packaging.

**Comment by DanielGibson** [comment] 2021-04-15 05:46
Dude, did you even read what I wrote?!

**There are Linux Distributions that are not based on debian.**

Some of them don't ship `SDL2Config.cmake` instead of `sdl2-config.cmake`.
`SDL2Config.cmake` does not support `SDL2_LIBRARIES` / `SDL2_INCLUDES`.

And, as much as I like debian and its derivatives: **Source ports also want to support those other distros**

**Comment by coldtobi** [comment] 2021-04-15 06:03
> Dude, did you even read what I wrote?!

Pardon? My remark was only regarding Ubuntu. I did not make any other statement about any other distribution.

**Comment by DanielGibson** [comment] 2021-04-15 06:12
Sorry, I think we're somehow talking past each other.

My point is: It seems like removing the custom `FindSDL2.cmake` **in the upstream repo** of source ports is bad because the alternatives break the build **either** on Arch Linux (and other distros/pkg managers shipping `SDL2Config.cmake`) **or** on debian-based distros that ship SDL2 < 2.0.12 (or other distros/pkg managers shipping `sdl2-config.cmake`, which includes Ubuntu 20.04).

So: Removing it with a patch in your **debian source packages** is fine, because obviously those only have to support debian-based distros, removing it here (or in dhewm3) is not, at least unless we find a solution to support both kinds of sdl2 cmake configs (from all SDL2 versions since at least 2.0.8).

**Comment by noabody** [comment] 2021-04-16 03:00
I was wondering if the solution I posited in the initial report would work in both situations.  I got the impression that ...

```
get_target_property(SDL2_INCLUDE_DIRS SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(SDL2_LIBRARIES SDL2::SDL2 IMPORTED_LOCATION_NOCONFIG)
```
... would bridge the gap by providing a value from SDL2Config.cmake that would conform to the format expected by using sdl2-config.cmake.

I mean, it won't return any value in the case of the latter but I figured ...
```
include_directories(${SDL2_INCLUDE_DIRS})
set(SDLx_LIBRARY ${SDL2_LIBRARIES})
```
would take care of the former.

But I really don't know much about, well, most of this stuff.  I just analyze things.

**Comment by DanielGibson** [comment] 2021-04-16 05:45
Ha, I had the same idea :)

I toyed around with `get_target_property()` a bit (on Windows with the vcpkg version of SDL2).
Getting the include directories is easy enough (`INTERFACE_INCLUDE_DIRECTORIES` worked for me as well), but getting the equivalent of SDL2_LIBRARIES seems a lot harder.
- TBH I'm not quite sure how exactly `SDL2_LIBRARIES` should look like for MSVC - when passing SDL2::SDL2 to `target_link_libraries()`, it seems to use the full path to SDL2.lib - **or** SDL2d.lib 
    - apparently the vcpkg package maintainer decided to provide a debug and a release version of SDL2, even though it shouldn't be necessary as, at least by default, SDL2 on Windows doesn't use the libc and thus should be unaffected by this debug vs release runtime mess
    - those paths were in the `IMPORTED_IMPLIB_DEBUG` and `IMPORTED_IMPLIB_RELEASE` properties of `SDL2::SDL2`
- `IMPORTED_LOCATION_NOCONFIG` does *not* work there (is not defined)
- For MinGW `SDL2_LIBRARIES` seems to contain a string like `-L${SDL2_LIBDIR} -lmingw32 -lSDL2main -lSDL2 -mwindows`, so it also contains the library search path and other libs to link against (and whatever `-mwindows` is) => it's not just libs to link against, but arguments for the (`ld`-like) linker.
- on my Linux machine it's just `-lSDL2`, but I can imagine that at least if SDL2 is not installed in a standard path it also contains `-L/sdl2/install/path`)

So it seems that piecing together a proper `SDL2_LIBRARIES` cmake variable from `SDL2::SDL2` is non-trivial, both because the target properties actually holding the relevant information vary, and because the necessary output format seems to depend on whether a GCC-like compiler or MSVC (Visual C++) is targeted.

One thing that seemed to work but is pretty dhewm3/RBDoom3BFG specific, was `set(SDLx_LIBRARY SDL2::SDL2)` (and, like you did, `get_target_property(SDL2_INCLUDE_DIRS SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES)`).
Then `target_link_libraries(RBDoom3BFG .... ${SDLx_LIBRARY} ...)` behaves just like `target_link_libaries(RBDoom3BFG .... SDL2::SDL2 ...)` which is valid and works.
I only dislike this because SDL2::SDL2 is quite different from that string `SDLx_LIBRARY` normally holds, and ideally I'd like to find a generic solution that can be included in SDL2's `SDL2Config.cmake`, so it provides `SDL2_LIBRARIES` and `SDL2_INCLUDE_DIRECTORIES` in addition to `SDL2::SDL2`, to make `sdl2-config.cmake` and `SDL2Config.cmake` functionally equivalent, as far as possible - that would un-screw the situation on the SDL2 side a bit, at least starting with the next release. (One good thing is that the only distros/pkg managers I know about that ship `SDL2Config.cmake` instead of `sdl2-config.cmake` are Arch Linux + derivatives and vcpkg, which tend to provide the latest release soon after it has been released, so that fix would reach people in the foreseeable future.)
And for a generic solution `set(SDL2_LIBRARIES SDL2::SDL2)` might not work, because maybe other peoples cmake files depend on `SDL2_LIBRARIES` being a normal variable holding a string, and do more fancy things with it than just passing it to `target_link_libraries()`...

**Comment by DanielGibson** [comment] 2021-04-16 05:59
Oh, forgot, @noabody can you paste what `IMPORTED_LOCATION_NOCONFIG` looks like on your system?

And ideally add this code: https://stackoverflow.com/a/56738858/14633188
to your CMakeLists.txt (somewhere after `find_package(SDL2 REQUIRED)`) and after that add `print_target_properties(SDL2::SDL2)`, run cmake and post the output from this?

It should print all the properties of `SDL2::SDL2` (well, at least as long as there's not multiple configurations like `IMPORTED_IMPLIB_DEBUG` and `_RELEASE`, the script can't handle those, but this shouldn't happen on Linux)

**Comment by noabody** [comment] 2021-04-16 16:00
Initially I got an error that ```print_target_properties``` is an unknown command so I spliced the information from [How to print all the properties of a target in cmake?](https://stackoverflow.com/questions/32183975/how-to-print-all-the-properties-of-a-target-in-cmake) into ```neo/CMakeLists.txt```.  I now get this output:

```
SDL2::SDL2 BINARY_DIR = /home/x264a/Dev/rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2 IMPORTED = TRUE
SDL2::SDL2 IMPORTED_CONFIGURATIONS = NOCONFIG
SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES = /usr/include;/usr/include/SDL2
SDL2::SDL2 LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 LOCATION_ = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 MACOSX_PACKAGE_LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 NAME = SDL2::SDL2
SDL2::SDL2 POSITION_INDEPENDENT_CODE = True
SDL2::SDL2 SOURCE_DIR = /home/x264a/Dev/rbdoom3bfg/src/rbdoom3bfg/neo
SDL2::SDL2 TYPE = SHARED_LIBRARY
SDL2::SDL2 VS_DEPLOYMENT_LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
```

**Comment by DanielGibson** [comment] 2021-04-16 17:55
Thanks!
I enhanced that function a bit so it also shows entries that end with `<CONFIG>`, can you run it again with this one?
https://gist.github.com/DanielGibson/ca02b1692499ce4911f7884dc0a67bbf#file-cmakelists-txt-L13-L59

**Comment by RobertBeckebans** [comment] 2021-04-16 19:28
Does this mean we have a better solution now?

**Comment by DanielGibson** [comment] 2021-04-16 21:49
Not yet, but I'm optimistic.

**Comment by noabody** [comment] 2021-04-17 01:38
```
SDL2::SDL2 BINARY_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2 BINARY_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2 IMPORTED = TRUE
SDL2::SDL2 IMPORTED_CONFIGURATIONS = NOCONFIG
SDL2::SDL2 IMPORTED_GLOBAL = FALSE
SDL2::SDL2 IMPORTED_LOCATION_NOCONFIG = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 IMPORTED_SONAME_NOCONFIG = libSDL2-2.0.so.0
SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES = /usr/include;/usr/include/SDL2
SDL2::SDL2 LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 LOCATION_NOCONFIG = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 MACOSX_PACKAGE_LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2 NAME = SDL2::SDL2
SDL2::SDL2 POSITION_INDEPENDENT_CODE = True
SDL2::SDL2 SOURCE_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2 SOURCE_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2 TYPE = SHARED_LIBRARY
SDL2::SDL2 TYPE = SHARED_LIBRARY
SDL2::SDL2 VS_DEPLOYMENT_LOCATION = /usr/lib/libSDL2-2.0.so.0.14.0
SDL2::SDL2main BINARY_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2main BINARY_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2main IMPORTED = TRUE
SDL2::SDL2main IMPORTED_CONFIGURATIONS = NOCONFIG
SDL2::SDL2main IMPORTED_GLOBAL = FALSE
SDL2::SDL2main IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG = C
SDL2::SDL2main IMPORTED_LOCATION_NOCONFIG = /usr/lib/libSDL2main.a
SDL2::SDL2main INTERFACE_INCLUDE_DIRECTORIES = /usr/include;/usr/include/SDL2
SDL2::SDL2main LOCATION = /usr/lib/libSDL2main.a
SDL2::SDL2main LOCATION = /usr/lib/libSDL2main.a
SDL2::SDL2main LOCATION_NOCONFIG = /usr/lib/libSDL2main.a
SDL2::SDL2main MACOSX_PACKAGE_LOCATION = /usr/lib/libSDL2main.a
SDL2::SDL2main NAME = SDL2::SDL2main
SDL2::SDL2main SOURCE_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2main SOURCE_DIR = /rbdoom3bfg/src/rbdoom3bfg/build
SDL2::SDL2main TYPE = STATIC_LIBRARY
SDL2::SDL2main TYPE = STATIC_LIBRARY
SDL2::SDL2main VS_DEPLOYMENT_LOCATION = /usr/lib/libSDL2main.a
```

**Comment by DanielGibson** [comment] 2021-04-17 23:18
Thanks!

**Comment by tapir** [comment] 2021-05-31 21:30
Not sure if it adds something to the discussion but this is also broken in vanilla Arch install.

**Comment by RobertBeckebans** [comment] 2021-07-08 06:49
Would https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/546/commits/f38cb29cf60b480f9a673f881034dfc250117747 break the build on Debian stable? I'm tending to accept to the Arch Linux fix.

**Comment by coldtobi** [comment] 2021-07-08 09:27
> Would [f38cb29](https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/f38cb29cf60b480f9a673f881034dfc250117747) break the build on Debian stable? I'm tending to accept to the Arch Linux fix.

Test-compiled f38cb29: No further tests done beside compiling,

- Debian unstable: **builds**
- Debian 11 (bullseye, next stable, relased this summer):  **builds**
- Debian 10 (buster, current stable): **DOES NOT BUILD**

```
-- Configuring done
CMake Error at CMakeLists.txt:1786 (add_executable):
  Target "rbdoom3bfg" links to target "SDL2::SDL2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

```

**Comment by DanielGibson** [comment] 2021-07-08 14:18
I'd suggest using something like
```
if(SDL2_LIBRARIES)
	include_directories(${SDL2_INCLUDE_DIRS})
	set(SDLx_LIBRARY ${SDL2_LIBRARIES})
else()
	set(SDLx_LIBRARY SDL2::SDL2)
endif()
```

**Comment by RobertBeckebans** [comment] 2023-02-25 11:45
Is this still a thing?

**Comment by xcom169** [comment] 2023-02-25 12:59
Not anymore

**Comment by RobertBeckebans** [comment] 2023-02-25 13:53
Thank you then I'm closing this.

**Closed by RobertBeckebans** 2023-02-25 13:53 UTC
