### ISSUE TITLE
Unable to initialize OpenGL

### ISSUE THREAD

**Issue by bageraz88** [RobertBeckebans/RBDOOM-3-BFG#800] opened 2023-08-07 14:39 UTC
Have issues with initializing OpenGL(?) Have tried rbdoom1.3 full package and had no problems
Windows 11
i3-4130
Nvidia GTX750 

----- R_InitOpenGL -----
...registered window class
...calling CDS: ok
...created window @ 0,0 (1920x1080)
...releasing DC: success
...destroying window
...resetting display
...calling CDS: ok
...created window @ 0,0 (1280x720)
...releasing DC: success
...destroying window
...resetting display
Unknown command 'vid_restart'
Unable to initialize OpenGL

**Comment by saehan-suh** [comment] 2023-08-17 18:14
Which version of RBDoom are you experiencing this issue with? 1.4 or 1.5?

**Comment by bageraz88** [comment] 2023-09-01 14:30
1.5.1

**Comment by RobertBeckebans** [comment] 2024-03-29 11:21
Duplicate of #844

**Closed by RobertBeckebans** 2024-03-29 11:21 UTC
